run:
  timeout: 5m
  show-stats: true
  skip-files: [ ]
  skip-dirs: [ ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G306
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - unnamedResult
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - ifshort
    - forcetypeassert
    - noctx
    - varnamelen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'fmt.Sprintf can be replaced with string addition'
  exclude-rules:
    - path: .*_test.go
      linters:
        - funlen
    - path: model.go
      text: type Dns(.+) should be DNS(.+)
    - path: params.go
      text: type Dns(.+) should be DNS(.+)
    - path: zz_gen_client.go
      text: method Dns(.+) should be DNS(.+)
    - path: zz_gen_client_test.go
      text: 'string `1234` has 56 occurrences, make it a constant'
    - path: zz_gen_client_test.go
      text: setupFakeAPI - result 0 \(\*net/http\.ServeMux\) is never used
    - path: gen/gen_test.go
      text: func `generate` is unused
    - path: gen/gen_test.go
      text: type `BaseName` is unused
    - path: .*/encoding/xml/.* # Disabled to a bug in musttag
      linters:
        - musttag
